# Generated by Django 4.1.4 on 2022-12-07 09:34

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0024_alter_customers_restaurants_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awardsdetails",
            name="user_id",
            field=models.ForeignKey(
                default=myapp.models.AwardsDetails.fetch_userid,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="awards",
                to="myapp.personaldetails",
            ),
        ),
        migrations.AlterField(
            model_name="certificatedetails",
            name="user_id",
            field=models.ForeignKey(
                default=myapp.models.CertificateDetails.fetch_userid,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="certificate",
                to="myapp.personaldetails",
            ),
        ),
        migrations.AlterField(
            model_name="educationaldetails",
            name="user_id",
            field=models.ForeignKey(
                default=myapp.models.EducationalDetails.fetch_userid,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="educational",
                to="myapp.personaldetails",
            ),
        ),
        migrations.AlterField(
            model_name="employmenthistory",
            name="user_id",
            field=models.ForeignKey(
                default=myapp.models.EmploymentHistory.fetch_userid,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="employement",
                to="myapp.personaldetails",
            ),
        ),
        migrations.AlterField(
            model_name="preferencesdetails",
            name="user_id",
            field=models.ForeignKey(
                default=myapp.models.PreferencesDetails.fetch_userid,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="preference",
                to="myapp.personaldetails",
            ),
        ),
        migrations.AlterField(
            model_name="workdetails",
            name="user_id",
            field=models.ForeignKey(
                default=myapp.models.WorkDetails.fetch_userid,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="work",
                to="myapp.personaldetails",
            ),
        ),
    ]
